[build]
dist = "dist"
public_url = "/"
target = "index.html"

[watch]
watch = ["src", "index.html", "styles"]

[serve]
addresses = ["127.0.0.1"]
open = false
port = 8080

[tools]
sass = "1.77"
wasm_bindgen = "0.2.118"

[[hooks]]
arguments = ["Frontend build complete"]
command = "echo"
stage = "post_build"
