//! Internationalization (I18n) module
//!
//! Provides Chinese/English bilingual support using `leptos_i18n`.
//! Translations are stored in JSON locale files (`locales/zh.json`, `locales/en.json`)
//! and checked at compile time. The current locale is persisted to `localStorage`.

// Include the code generated by `leptos_i18n_build` in `build.rs`.
// This creates a sub-module `i18n` containing `Locale`, `I18nKeys`, `use_i18n`, `t!`, etc.
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

use leptos::prelude::*;

// Re-export the generated `Locale` type and the `use_i18n` function
// so that other modules can simply `use crate::i18n::*;`.
pub use i18n::*;

// =============================================================================
// localStorage persistence
// =============================================================================

/// localStorage key for persisting the locale preference.
const LOCALE_STORAGE_KEY: &str = "chat_app_locale";

/// Detect the initial locale from localStorage or browser language.
pub fn detect_initial_locale() -> Locale {
  if let Some(window) = web_sys::window() {
    // Try localStorage first
    if let Ok(Some(storage)) = window.local_storage()
      && let Ok(Some(val)) = storage.get_item(LOCALE_STORAGE_KEY)
    {
      return locale_from_str(&val);
    }
    // Fallback: detect browser language
    if let Some(lang) = window.navigator().language()
      && lang.starts_with("en")
    {
      return Locale::en;
    }
  }
  Locale::zh
}

/// Save locale to localStorage.
pub fn save_locale(locale: Locale) {
  if let Some(window) = web_sys::window()
    && let Ok(Some(storage)) = window.local_storage()
  {
    let _ = storage.set_item(LOCALE_STORAGE_KEY, locale_tag(locale));
  }
}

/// Parse a locale from a loose string (e.g. from localStorage).
pub fn locale_from_str(s: &str) -> Locale {
  match s {
    "en" | "en-US" | "en-GB" | "English" => Locale::en,
    _ => Locale::zh,
  }
}

/// BCP-47 language tag for a locale.
pub fn locale_tag(locale: Locale) -> &'static str {
  match locale {
    Locale::zh => "zh-CN",
    Locale::en => "en",
  }
}

/// Display name in the locale's own language.
pub fn locale_display_name(locale: Locale) -> &'static str {
  match locale {
    Locale::zh => "Chinese",
    Locale::en => "English",
  }
}

/// Provide the I18n context at the root of the component tree.
///
/// Call this once in the root `App` component. It reads the persisted locale
/// from localStorage (or detects the browser language) and provides the
/// `leptos_i18n` context so that `t!(i18n, key)` works everywhere.
pub fn provide_i18n_context_with_persistence() {
  // Provide the context with default options
  let i18n_ctx = leptos_i18n::context::provide_i18n_context_with_options_inner::<Locale>(
    leptos_i18n::context::I18nContextOptions::default(),
  );

  // Override with the locale detected from localStorage / browser language
  let initial = detect_initial_locale();
  i18n_ctx.set_locale(initial);

  // Watch for locale changes and persist to localStorage
  Effect::new(move |_| {
    let current = i18n_ctx.get_locale();
    save_locale(current);
  });
}

/// Switch the current locale (the Effect above will persist it).
pub fn switch_locale(locale: Locale) {
  let ctx = i18n::use_i18n();
  ctx.set_locale(locale);
}

/// Type alias for the I18n context, for convenience.
pub type I18nContext = leptos_i18n::context::I18nContext<Locale>;

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_locale_from_str_chinese_default() {
    assert!(matches!(locale_from_str("zh"), Locale::zh));
    assert!(matches!(locale_from_str("zh-CN"), Locale::zh));
    assert!(matches!(locale_from_str("unknown"), Locale::zh));
    assert!(matches!(locale_from_str(""), Locale::zh));
  }

  #[test]
  fn test_locale_from_str_english() {
    assert!(matches!(locale_from_str("en"), Locale::en));
    assert!(matches!(locale_from_str("en-US"), Locale::en));
    assert!(matches!(locale_from_str("en-GB"), Locale::en));
    assert!(matches!(locale_from_str("English"), Locale::en));
  }

  #[test]
  fn test_locale_tag() {
    assert_eq!(locale_tag(Locale::zh), "zh-CN");
    assert_eq!(locale_tag(Locale::en), "en");
  }

  #[test]
  fn test_locale_display_name() {
    assert_eq!(locale_display_name(Locale::zh), "Chinese");
    assert_eq!(locale_display_name(Locale::en), "English");
  }
}
