[workspace]
members = ["sdp", "chat", "message"]
resolver = "2"

[workspace.dependencies]
serde = {version = "1.0.190", features = ["derive"]}
serde_json = "1.0.108"
nanoid = "0.4.0"
futures = "0.3.29"
