[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
getrandom = { version = "0.2.8", features = ["js"] }
gloo-console = "0.2.3"
gloo-events = "0.1.2"
gloo-render = "0.1.1"
js-sys = "0.3.60"
rand = "0.8.5"
stylist = { version = "0.11.0", features = ["yew_integration"] }
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Document", "Element", "Window", "HtmlCanvasElement", "CanvasRenderingContext2d"] }
yew = { version = "0.20.0", features = ["csr"] }
