[workspace]
members = ["sdp", "chat", "message"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.30"
gloo-console = "0.3.0"
gloo-net = "0.5.0"
nanoid = "0.4.0"
serde = {version = "1.0.195", features = ["derive"]}
serde_json = "1.0.111"
