[workspace]
members = ["sdp", "chat", "message"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.30"
gloo-console = "0.3.0"
gloo-net = "0.6.0"
nanoid = "0.4.0"
serde = {version = "1.0.209", features = ["derive"]}
serde_json = "1.0.127"
web-sys = "0.3.70"
