[package]
edition = "2021"
name = "chat"
version = "0.1.0"

[features]
dev = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.4"
bounce = "0.9.0"
chrono = "0.4.31"
derivative = "2.2.0"
fake = {version = "2.8.0", features = ["derive", "uuid", "chrono"]}
futures = "0.3.28"
getrandom = {version = "0.2.10", features = ["js"]}
gloo-console = "0.3.0"
gloo-events = "0.2.0"
gloo-render = "0.2.0"
gloo-timers = "0.3.0"
gloo-utils = "0.2.0"
indexmap = "2.0.2"
js-sys = "0.3.64"
nanoid = "0.4.0"
pinyin = "0.10.0"
rand = "0.8.5"
serde = {version = "1.0.189", features = ["derive"]}
serde_json = "1.0.107"
stylist = {version = "0.13.0", features = ["yew_integration"]}
unicode-segmentation = "1.10.1"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = {version = "0.3.64", features = [
  "Document",
  "Element",
  "Window",
  "HtmlCanvasElement",
  "CanvasRenderingContext2d",
  "DomStringMap",
  "HtmlTextAreaElement",
  "Blob",
  "BlobEvent",
  "BlobPropertyBag",
  "Url",
  "MediaRecorder",
  "MediaStreamConstraints",
  "AudioContext",
  "AudioBuffer",
  "AnalyserNode",
  "AudioContextOptions",
  "MediaStream",
  "MediaStreamTrack",
  "MediaDevices",
  "Navigator",
  "EventListener",
  "EventTarget",
  "BaseAudioContext",
  "MediaStreamAudioSourceNode",
  "HtmlAudioElement",
  "CssStyleDeclaration",
  "MessageEvent",
  "RtcPeerConnection",
  "RtcSignalingState",
  "RtcSdpType",
  "RtcSessionDescriptionInit",
  "RtcPeerConnectionIceEvent",
  "RtcIceCandidate",
  "RtcDataChannel",
  "RtcDataChannelEvent",
]}
yew = {version = "0.21.0", features = ["csr"]}
yew-hooks = "0.3.0"
yew-router = "0.18.0"
yew_icons = {version = "0.8.0", features = [
  "HeroiconsSolidUserGroup",
  "BootstrapCameraVideoFill",
  "LucideSettings",
  "HeroiconsMiniSolidHome",
  "FontAwesomeSolidVolumeHigh",
  "FontAwesomeSolidVolumeXmark",
  "BootstrapSearch",
  "FontAwesomeSolidXmark",
  "BootstrapEmojiSmile",
  "BootstrapSendFill",
  "HeroiconsSolidMicrophone",
  "FontAwesomeRegularImages",
  "BootstrapCheckCircleFill",
  "BootstrapInfoCircleFill",
  "BootstrapPauseFill",
  "BootstrapPlayFill",
  "BootstrapSunFill",
  "BootstrapMoonStarsFill",
]}
