[workspace]
members = ["sdp", "chat", "message"]
resolver = "2"

[workspace.dependencies]
futures = "0.3.31"
gloo-console = "0.3.0"
gloo-net = "0.6.0"
nanoid = "0.4.0"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
web-sys = "0.3.70"
bincode = "1.3.3"
chrono = { version = "0.4.38", features = ["serde"] }
