[package]
edition = "2021"
name = "chat"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bounce = "0.6.1"
derivative = "2.2.0"
getrandom = {version = "0.2.8", features = ["js"]}
gloo-console = "0.2.3"
gloo-events = "0.1.2"
gloo-render = "0.1.1"
js-sys = "0.3.60"
rand = "0.8.5"
stylist = {version = "0.11.0", features = ["yew_integration"]}
wasm-bindgen = "0.2.83"
web-sys = {version = "0.3.60", features = ["Document", "Element", "Window", "HtmlCanvasElement", "CanvasRenderingContext2d"]}
yew = {version = "0.20.0", features = ["csr"]}
yew-hooks = "0.2.0"
yew-router = "0.17.0"
yew_icons = {version = "0.7.2", features = [
  "HeroiconsSolidUserGroup",
  "BootstrapCameraVideoFill",
  "LucideSettings",
  "HeroiconsMiniSolidHome",
  "FontAwesomeSolidVolumeHigh",
  "FontAwesomeSolidVolumeXmark",
]}
