[package]
edition = "2021"
name = "protocol"
version = "0.1.0"

[dependencies]
bincode = {workspace = true}
bit-vec = "0.8.0"
encoding_rs = {version = "0.8.34", features = ["serde"]}
nanoid = {workspace = true}
serde = {workspace = true, features = ["derive"]}
