[package]
name = "message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
nanoid = {workspace = true}
futures = {workspace = true}
gloo-console = {workspace = true}
async-broadcast = {workspace = true}
gloo-net = {workspace = true}
