[package]
edition = "2021"
name = "message"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
gloo-console = {workspace = true}
gloo-net = {workspace = true}
nanoid = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
bincode = {workspace = true}
