[package]
edition = "2021"
name = "message"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
gloo-console = {workspace = true}
gloo-net = {workspace = true}
nanoid = {workspace = true}
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
bincode = {workspace = true}
chrono = {workspace = true, features = ["serde"]}
encoding_rs = { version = "0.8.34", features = ["serde"] }
bit-vec = "0.8.0"
