/**
 * Theater room E2E coverage (Wave P2-5).
 *
 * The sidebar's "Create room" button opens `CreateRoomModal`. Picking
 * the Theater radio (`data-testid="room-type-theater"`) and submitting
 * sends a `CreateRoom { room_type: Theater }` to the signaling server.
 * The frontend then:
 *   * receives `RoomCreated` (handler stores the room and sets the
 *     creator as Owner),
 *   * sets `active_conversation = ConversationId::Room(room_id)`,
 *   * causes `HomePage` to render `<TheaterPage>` (because the active
 *     conversation's room_type is Theater).
 *
 * Owner-side coverage:
 *   * `theater-page` is mounted with the room's name in its header.
 *   * `theater-source-picker` (the upload-local / share-screen / URL
 *     trio) is visible — the owner can choose a source.
 *   * The chat tab is wired and dispatching a `danmaku-input` /
 *     `theater-chat-input` send creates a `theater-chat-bubble`.
 *   * URL picker rejects non-http(s) URLs with a visible error
 *     (G27 partial).
 *   * Picking a local video file via `setInputFiles` mounts the
 *     `<video>` element and binds it to a `blob:` object URL whose
 *     `videoWidth > 0` once decode kicks in (G27 — uses
 *     `e2e/assets/tiny.webm`, a 536-byte 2×2 VP8 stub generated by
 *     ffmpeg).
 *
 * The cross-peer "viewer joins" + "danmaku round-trip" assertions
 * are deferred to a follow-up: they need an additional join flow on
 * pageB and a successful WebRTC publish_to_peers handshake before
 * the viewer's `<video>` element receives a frame. Owner-side
 * playback is the higher-value first guard, since it locks down
 * the source picker → `<video>` element binding that gates every
 * downstream theater feature — and surfaces the
 * `has_video_source` chicken-and-egg bug between the parent
 * `<Show>` and the `node_ref`-dependent binding effect (fixed in
 * the same commit as this spec by splitting the player effect in
 * two).
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { sel } from '../utils/selectors.ts';
import { registerAndLogin } from '../fixtures/helpers.ts';
import { expect, test } from '../fixtures/test-base.ts';
import type { Page } from '@playwright/test';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TINY_WEBM = path.resolve(__dirname, '..', 'assets', 'tiny.webm');

/**
 * Create a Theater-type room as `page`'s logged-in user.
 *
 * Mirrors the `createRoom` helper but flips the radio to Theater and
 * waits for the page to auto-mount `<TheaterPage>` (the creator is
 * auto-switched into the room and the home page swaps ChatView →
 * TheaterPage based on `active_conversation`'s room type).
 */
async function createTheaterRoom(
  page: Page,
  options: { name?: string } = {},
): Promise<{ name: string }> {
  const name = options.name ?? `theater-${Math.random().toString(36).slice(2, 8)}`;

  await page.locator(sel.sidebarRoomCreateBtn).click();
  const modal = page.locator(sel.createRoomModal);
  await expect(modal).toBeVisible({ timeout: 10_000 });

  await modal.locator(sel.createRoomName).fill(name);
  // Flip the room type radio to Theater. The radio itself is hidden
  // behind a styled label; click the input element directly.
  await modal.locator(sel.createRoomTypeTheater).click();

  // The Theater-only hint mounts once the radio is on; serves as a
  // readiness oracle that the room-type signal has flipped.
  await expect(modal.locator('[data-testid="theater-extra-hint"]')).toBeVisible({
    timeout: 3_000,
  });

  await modal.locator(sel.createRoomSubmit).click();
  await expect(modal).toBeHidden({ timeout: 10_000 });

  // TheaterPage auto-mounts because `RoomCreated` sets
  // `active_conversation` to the new room id and the room_type is
  // Theater (see `home_page.rs`).
  await expect(page.locator(sel.theaterPage)).toBeVisible({ timeout: 15_000 });

  return { name };
}

test.describe('theater room', () => {
  test('creator lands on theater-page with the source picker visible', async ({
    pageA,
    server,
  }) => {
    await registerAndLogin(pageA, server, { hint: 'th-cr' });
    const { name } = await createTheaterRoom(pageA);

    const page = pageA.locator(sel.theaterPage);
    await expect(page).toBeVisible();
    // Header carries the room name (the only `h2` inside the
    // theater-page header).
    await expect(page.locator('header h2').first()).toContainText(name);

    // Source picker is rendered for the owner before any video is
    // chosen — confirms the player slot resolved to the empty state
    // rather than a stale ChatView.
    await expect(pageA.locator(sel.theaterSourcePicker)).toBeVisible({ timeout: 10_000 });

    // The picker's three primary affordances are all present.
    await expect(pageA.locator(sel.theaterSourceLocal)).toBeVisible();
    await expect(pageA.locator(sel.theaterSourceScreen)).toBeVisible();
    await expect(pageA.locator(sel.theaterSourceUrl)).toBeVisible();
  });

  test('chat tab dispatches a message and renders a theater-chat-bubble', async ({
    pageA,
    server,
  }) => {
    await registerAndLogin(pageA, server, { hint: 'th-chat' });
    await createTheaterRoom(pageA);

    // Activate the chat tab — `theater-tab-chat` is the default, but
    // click it anyway so the test is robust against future tab-state
    // changes that might land the user on Members first.
    await pageA.locator(sel.theaterTabChat).click();
    await expect(pageA.locator(sel.theaterChatPanel)).toBeVisible({ timeout: 5_000 });

    const tag = Date.now().toString(36);
    const message = `theater-msg-${tag}`;
    await pageA.locator(sel.theaterChatInput).fill(message);
    await pageA.locator(sel.theaterChatSend).click();

    // The owner's own send appears in the chat panel as a
    // theater-chat-bubble.
    const bubble = pageA
      .locator(sel.theaterChatPanel)
      .locator('[data-testid="theater-chat-bubble"]', { hasText: message })
      .first();
    await expect(bubble).toBeVisible({ timeout: 10_000 });
  });

  test('URL picker rejects non-http(s) URLs with a visible error (G27)', async ({
    pageA,
    server,
  }) => {
    await registerAndLogin(pageA, server, { hint: 'th-url' });
    await createTheaterRoom(pageA);

    // Toggle the URL form open.
    await pageA.locator(sel.theaterSourceUrl).click();
    const urlInput = pageA.locator('[data-testid="theater-source-url-input"]');
    await expect(urlInput).toBeVisible({ timeout: 5_000 });

    // The native `<input type="url">` validation accepts any
    // RFC 3986 URI (incl. `ftp://`), so a non-http(s) URL passes the
    // browser-level check and the form's `submit` event fires —
    // which lets the picker's own
    // `starts_with("http://") || starts_with("https://")` branch
    // surface its alert.
    await urlInput.fill('ftp://example.test');
    await pageA.locator('[data-testid="theater-source-url-submit"]').click();

    const error = pageA
      .locator(sel.theaterSourcePicker)
      .locator('.theater-source-picker__error');
    await expect(error).toBeVisible({ timeout: 3_000 });
    await expect(error).not.toBeEmpty();
    // Form value preserved so the user can correct the typo.
    await expect(urlInput).toHaveValue('ftp://example.test');
  });

  test('owner picks a local video file and the <video> element mounts with a real frame (G27)', async ({
    pageA,
    server,
  }) => {
    await registerAndLogin(pageA, server, { hint: 'th-local' });
    await createTheaterRoom(pageA);

    // Feed the hidden `<input type="file">` directly. The picker
    // converts the File to an object URL and dispatches a
    // VideoSource::LocalFile, which the player binds to `<video>.src`.
    //
    // `setInputFiles` requires a real File-like payload — read the
    // fixture into a buffer + supply name + mimeType.
    await pageA.locator(sel.theaterSourceLocalInput).setInputFiles({
      name: 'tiny.webm',
      mimeType: 'video/webm',
      buffer: (await import('node:fs')).readFileSync(TINY_WEBM),
    });

    // `<video>` materialises only after `state.has_video_source`
    // flips true. With G27's two-effect split in
    // theater_video_player.rs, the flag now flips on `source.set(...)`
    // independently of the `<video>` `node_ref` being populated,
    // so the gated element gets to mount on the next reactive tick.
    const video = pageA.locator(sel.theaterVideo);
    await expect(video).toBeVisible({ timeout: 10_000 });

    // Confirm the player actually bound the picked file to the
    // element's `src` (object URL pattern: `blob:http://…/<uuid>`).
    await expect
      .poll(
        async () =>
          video.evaluate((el: HTMLVideoElement) => ({
            srcPrefix: el.src.slice(0, 5),
            width: el.videoWidth,
            readyState: el.readyState,
          })),
        { timeout: 10_000 },
      )
      .toMatchObject({
        srcPrefix: 'blob:',
        // The single-frame VP8 stub is 2×2; Chromium reports
        // videoWidth=2 the moment loadedmetadata fires.
        width: 2,
        readyState: expect.any(Number),
      });

    // readyState should reach at least HAVE_CURRENT_DATA (2) so we
    // know the first frame is decoded rather than the element being
    // stuck at HAVE_METADATA (1).
    const readyState = await video.evaluate((el: HTMLVideoElement) => el.readyState);
    expect(readyState).toBeGreaterThanOrEqual(2);
  });

  test('viewer joins the theater room and receives the owner stream (P2-5)', async ({
    pageA,
    pageB,
    server,
  }) => {
    // ── Owner (A): create theater + pick local video ──────────────────
    await registerAndLogin(pageA, server, { hint: 'th-vj-a' });
    await registerAndLogin(pageB, server, { hint: 'th-vj-b' });
    const { name } = await createTheaterRoom(pageA);

    // Owner picks the local video file so a MediaStream is captured
    // and ready to be pushed to joining viewers.
    await pageA.locator(sel.theaterSourceLocalInput).setInputFiles({
      name: 'tiny.webm',
      mimeType: 'video/webm',
      buffer: (await import('node:fs')).readFileSync(TINY_WEBM),
    });

    // Wait for the owner's <video> to mount and decode at least one
    // frame — this confirms the stream is captured and publishable.
    const ownerVideo = pageA.locator(sel.theaterVideo);
    await expect(ownerVideo).toBeVisible({ timeout: 10_000 });
    await expect
      .poll(
        async () => ownerVideo.evaluate((el: HTMLVideoElement) => el.readyState),
        { timeout: 10_000 },
      )
      .toBeGreaterThanOrEqual(2);

    // Debug: collect console logs from both pages to diagnose WebRTC flow
    const logsA: string[] = [];
    const logsB: string[] = [];
    pageA.on('console', (msg) => { if (msg.text().includes('[webrtc]') || msg.text().includes('[theater]')) logsA.push(msg.text()); });
    pageB.on('console', (msg) => { if (msg.text().includes('[webrtc]') || msg.text().includes('[theater]')) logsB.push(msg.text()); });

    // ── Viewer (B): join the theater room ─────────────────────────────
    // The room appears in B's sidebar via `RoomListUpdate`. Click the
    // join button, which triggers `JoinRoom` → `RoomJoined` and sets
    // `active_conversation` to the theater room. The home page then
    // renders `<TheaterPage>` instead of `<ChatView>`.
    const itemOnB = pageB.locator(
      `${sel.sidebarRoomItem}[data-room-name="${name}"]`,
    );
    await expect(itemOnB).toBeVisible({ timeout: 15_000 });
    await itemOnB.locator(sel.sidebarRoomJoinBtn).click();
    await expect(itemOnB).toHaveAttribute('data-joined', 'true', { timeout: 15_000 });

    // TheaterPage mounts on B because the room_type is Theater.
    await expect(pageB.locator(sel.theaterPage)).toBeVisible({ timeout: 15_000 });

    // Wait a bit for the auto-connect to happen
    await pageA.waitForTimeout(5_000);

    // Debug: check owner's peer connection state
    const ownerDebug = await pageA.evaluate(() => {
      const w = (window as unknown as { __webrtc_debug?: () => unknown }).__webrtc_debug;
      return w ? w() : 'no debug hook';
    });
    console.log('[DEBUG] Owner WebRTC state:', JSON.stringify(ownerDebug));
    console.log('[DEBUG] Owner logs:', logsA);
    console.log('[DEBUG] Viewer logs:', logsB);

    // The viewer initially sees the "waiting for stream" placeholder
    // until the WebRTC handshake completes and the owner pushes the
    // stream. Once `ontrack` fires, `has_video_source` flips and the
    // `<video>` element mounts with `srcObject` bound.
    const viewerVideo = pageB.locator(sel.theaterVideo);
    await expect(viewerVideo).toBeVisible({ timeout: 30_000 });

    // Confirm the viewer's <video> has a MediaStream bound via
    // srcObject (not a blob: URL like the owner's local file).
    await expect
      .poll(
        async () =>
          viewerVideo.evaluate((el: HTMLVideoElement) => {
            const srcObj = (el as unknown as { srcObject: MediaStream | null }).srcObject;
            return {
              hasSrcObject: srcObj !== null,
              trackCount: srcObj ? srcObj.getTracks().length : 0,
            };
          }),
        { timeout: 30_000 },
      )
      .toMatchObject({
        hasSrcObject: true,
        trackCount: expect.any(Number),
      });

    // The viewer's track count should be at least 1 (video track).
    const trackCount = await viewerVideo.evaluate((el: HTMLVideoElement) => {
      const srcObj = (el as unknown as { srcObject: MediaStream | null }).srcObject;
      return srcObj ? srcObj.getTracks().length : 0;
    });
    expect(trackCount).toBeGreaterThanOrEqual(1);
  });
});
